# Changes here will be overwritten by Copier
_commit: v1.2.1-94-gaecf024
_src_path: ./python-project-template
author_email: name@you.com
author_name: Your Name
create_example_module: true
custom_install: true
include_notebooks: true
module_name: example_module
mypy_type_checking: basic
preferred_linter: pylint
project_license: MIT
project_name: example_project
use_gitlfs: none
use_isort: true
